/*
 *  Created on: Jul 27              2019
 *  Author: WanQing
 *  E-mail: 1109162935@qq.com
 */
//@formatter:off
static void *opcode_targets[OP_MAX] = {
  &&TARGET_NIL           ,
  &&TARGET_MOVE          ,
  &&TARGET_CONST         ,
  &&TARGET_GLOBAL        ,
  &&TARGET_SETGLOBAL     ,
  &&TARGET_LOADNIL       ,
  &&TARGET_UPVAL         ,
  &&TARGET_SETUPVAL      ,
  &&TARGET_NEWTABLE      ,
  &&TARGET_NEWLIST       ,
  &&TARGET_NEWCLASS      ,
  &&TARGET_UNM           ,
  &&TARGET_BNOT          ,
  &&TARGET_NOT           ,
  &&TARGET_LEN           ,
  &&TARGET_JMP           ,
  &&TARGET_TEST          ,
  &&TARGET_FORLOOP       ,
  &&TARGET_FORPREP       ,
  &&TARGET_RETURN        ,
  &&TARGET_TFORCALL      ,
  &&TARGET_TFORLOOP      ,
  &&TARGET_CLOSURE       ,
  &&TARGET_BUILD_METH    ,
  &&TARGET_VARARG        ,
  &&TARGET_LOADBOOL      ,
  &&TARGET_GETTABUP      ,
  &&TARGET_GET_ATTR      ,
  &&TARGET_SETTABUP      ,
  &&TARGET_SET_ATTR      ,
  &&TARGET_GETTABGL      ,
  &&TARGET_SETUP_EXCEPT          ,
  &&TARGET_ADD           ,
  &&TARGET_SUB           ,
  &&TARGET_MUL           ,
  &&TARGET_MOD           ,
  &&TARGET_POW           ,
  &&TARGET_DIV           ,
  &&TARGET_IDIV          ,
  &&TARGET_BAND          ,
  &&TARGET_BOR           ,
  &&TARGET_BXOR          ,
  &&TARGET_SHL           ,
  &&TARGET_SHR           ,
  &&TARGET_CONCAT        ,
  &&TARGET_EQ            ,
  &&TARGET_LT            ,
  &&TARGET_LE            ,
  &&TARGET_TESTSET       ,
  &&TARGET_CALL          ,
  &&TARGET_CALL_KW      ,
  &&TARGET_SETLIST       ,
  &&TARGET_JMP_IF_FALSE  ,
  &&TARGET_JMP_IF_TRUE 	 ,
};
//@formatter:on
